<!DOCTYPE html>
<html lang="pt">
    <head>

        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Geren. de Atividades | {{ title }}</title>

        <!-- Bootstrap core CSS -->
        <!-- Custom styles for this template -->

        <link href="{{ url('css/bootstrap.css') }}" rel="stylesheet">
        <!--<link href="css/bootstrap-theme.min.css" rel="stylesheet">-->
        <link href="{{ url('css/carousel.css') }}" rel="stylesheet">
        <link href="{{ url('css/customizations.css') }}" rel="stylesheet">
        <link href="{{ url('css/bootstrap-tagsinput.css') }}" rel="stylesheet">
        <link href="{{ url('css/jquery.timepicker.css') }}" rel="stylesheet">
        <link href="{{ url('css/datepicker.css') }}" rel="stylesheet">


        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{{ url('js/jquery-1.10.2.min.js') }}"></script>
        <script src="{{ url('js/bootstrap.min.js') }}"></script>
        <script src="{{ url('js/holder.js') }}"></script>
        <script src="{{ url('js/bootstrap-tagsinput.min.js') }}"></script>
        <script src="{{ url('js/jquery.timepicker.min.js') }}"></script>
        <script src="{{ url('js/bootstrap-datepicker.js') }}"></script>

        {% endblock %}

    </head>
    <!-- NAVBAR
    ================================================== -->
    <body>
        <div class="navbar navbar-default navbar-fixed-top navbar-inverse"role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse navbar-inverse-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('') }}">Inicio</a></li>
                    <!--<li><a  href="index.php?p=pages/open/menu.php" >Cardápio</a></li>-->

                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                            Administrativo
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url('usercrud') }}">Usuarios</a></li>
                            <li><a href="{{ url('activitytype')}}">Tipos de Atividade</a></li>
                            <li><a href="{{ url('holiday')}}">Feriados</a></li>
                        </ul>
                    </li>
                    <li><a href="{{ url('activities')}}">Atividades</a></li>
                    <li><a href="{{ url('report')}}">Relatórios</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                            {{_session.getUser().getName()}}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{url('security/logout')}}">Sair</a></li>
                            {% if _session.getCanStartWork() %}
                            <li><a href="{{url('work/start')}}">Iniciar dia</a></li>
                            {% endif %}
                            {% if _session.getCanEndWork() %}
                            <li><a href="{{url('work/end')}}">Terminar dia</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="container">
            <hr />
            {% block content %}
            {% endblock %}
        </div>
        <!-- FOOTER -->
        <footer class="bs-footer" style="clear: both;margin-top: 10px;">
            <div class="navbar navbar-default navbar-inverse" >
                <div class="col-lg-4">
                </div>
                <div class="col-lg-4">
                </div> 
                <div class="col-lg-4 text-right">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Topo</a></li>
                    </ul>
                </div>
            </div>  
        </footer>
        <script type="text/javascript">
            $('.input-date').datepicker();
        </script>
    </body>
</html>
