<!DOCTYPE html>
<html lang="en">
    <head>

        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Geren. de Atividades</title>

        <!-- Bootstrap core CSS -->
        <!-- Custom styles for this template -->

        <link href="{{ url('css/bootstrap.css') }}" rel="stylesheet">
        <!--<link href="css/bootstrap-theme.min.css" rel="stylesheet">-->
        <link href="{{ url('css/carousel.css') }}" rel="stylesheet">
        <link href="{{ url('css/customizations.css') }}" rel="stylesheet">
        <link href="{{ url('css/bootstrap-tagsinput.css') }}" rel="stylesheet">


        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{{ url('js/jquery-1.11.1.min.js') }}"></script>
        <script src="{{ url('js/bootstrap.min.js') }}"></script>
        <script src="{{ url('js/holder.js') }}"></script>
        <script src="{{ url('js/bootstrap-tagsinput.min.js') }}"></script>

        {% endblock %}

    </head>
    <!-- NAVBAR
    ================================================== -->
    <body>
        <div class="navbar navbar-default navbar-fixed-top navbar-inverse"role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Login</a>
            </div>
        </div>
        <div class="container">
            <hr />
            {% block content %}
            {% endblock %}
        </div>
        <!-- FOOTER -->
        <footer style="clear: both">
            <div class="navbar navbar-default navbar-inverse" >
                <div class="col-lg-4">
                </div>
                <div class="col-lg-4">
                </div> 
                <div class="col-lg-4 text-right">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Topo</a></li>
                    </ul>
                </div>
            </div>  
        </footer>
    </body>
</html>