<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{{ title }} | {{ action }}</title>

        <!-- Bootstrap core CSS -->
        <!-- Custom styles for this template -->

        <link href="{{ url("css/bootstrap.css") }}" rel="stylesheet" />
        
        <link href="{{ url("css/carousel.css") }}" rel="stylesheet" />
        <link href="{{ url("css/customizations.css") }}" rel="stylesheet" />

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        {% endblock %}
    </head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('') }}">Fornalha Vinhedo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a  href="{{ url('menu') }}">Cardápio</a></li>
                    <li><a href="{{ url('deals') }}">Promoções</a></li>
                    <li><a href="{{ url('map') }}">Localizaçao</a></li>
                    <li><a href="{{ url('static/contact') }}">Contato</a></li>
                    <li><a href="{{ url('static/aboutus') }}">Quem somos</a></li>
                </ul>
            </div>
        </div>

        <div class="container">
            <hr />
            {% block content %}
            {% endblock %}
        </div>
        
        <!-- FOOTER -->
        <footer class="bs-footer" style="background: #006742;clear: both">
            <hr class="" />
            <div class="container marketing">
                <div class="col-lg-4">
                    <img class="img-rounded" src="{{ url("img/layout/logo.gif") }}" alt="Generic placeholder image">
                </div>
                <div class="col-lg-4">
                    <p class="">Tv Santa Cruz, 1404 - final da indepedência - Pinheirinho</p>
                    <p class="">Vinhedo, SP | CEP: 13280-000</p>
                    <p class="">(19) 3876-2588</p>
                </div> 
                <div class="col-lg-4 text-right">
                    <a href="#">Topo</a> <br />
                    <a href="{{ url('admin') }}">Administração</a>
                </div>
            </div>
        </footer>


        <!-- Bootstrap core JavaScript -->
        <script src="{{ url('js/jquery-1.10.2.min.js') }}"></script>
        <script src="{{ url('js/bootstrap.min.js') }}"></script>
        <script src="{{ url('js/holder.js') }}"></script>

    </body>
</html>