{% extends "template/open.phtml" %}
{% block content %}
<div class="alert alert-danger col-lg-6 col-md-8 col-xs-11" style="margin: auto;float: none;">
    <h2>Erro 404: Recurso não encontrando</h2>
    <p>O recurso requisitado não se encontra disponível, pode ter sido movido ou excluído.</p>
    <p class="pull-right">Para continuar clique <a href="{{ url('')}}">aqui</a>.</p>
    <span class="clearfix"></span>
</div>
{% endblock %}