{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('report/index') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <div class="well row">
                <fieldset>
                    <legend>Relatórios | Atividades</legend>
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="col-lg-1 col-md-1">Data</th>
                                <th class="col-lg-2 col-md-2">Cliente</th>
                                <th class="col-lg-5 col-md-5">Atividade</th>
                                <th class="col-lg-2 col-md-2">
                                    <span class="hidden-xs">Alocado</span>
                                    <span class="visible-xs">Alo.</span>
                                </th>
                                <th class="col-lg-2 col-md-2">
                                    <span class="hidden-xs">Finalizada</span>
                                    <span class="visible-xs">Fin.</span>
                                </th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for r in results.getData() %}
                            <tr>
                                <td>{{ formatDate(r.getDate(), 'day-only') }}</td>
                                <td>{{ r.getCustomerName() }}</td>
                                <td><a href="{{ url('activities/view/'~r.getActivityId() )}}">{{r.getActivityName()}}</a></td>
                                <td>{{ r.getAllocated() }}</td>
                                <td>{{ r.isFinished() ? 'SIM':'NAO' }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="4" class="text-right ">
                        <p class="help-block">Total {{results.getTotal()}} ({{results.getFinished()}} foram finalizadas)</p> 
                        </th>
                        </tr>
                        </tfoot>
                    </table>
                </fieldset>
            </div>
        </div>
    </div>
</div>
{% endblock %}