{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('report/index') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <p>{{ _session.getMessage() }}</ p>
            <div class="well">
                <form action="#" id="paramsForm" method="get" class="form-inline">
                    <fieldset>
                        <legend>Relatório</legend>
                        <div class="col-lg-10 col-lg-offset-1">
                            <div class="row" style=" margin: 10px 0px;">
                                <label for="report_selection" 
                                       class="control-label" style="display: block">Selecione o relatório</label>
                                <select name="report_selection" id="report_selection" 
                                        class="form-control"
                                        style="width: 100%;">
                                    <option value="" selected="selected">---Selecione---</option>
                                    <option value="1" {{ params['report'] == 1 ? 'selected' : ''}} >Usuários</option>
                                    <option value="2" {{ params['report'] == 2 ? 'selected' : ''}} >Atividades</option>
                                    <option value="3" {{ params['report'] == 3 ? 'selected' : ''}} >Tipos de atividade</option>
                                    <option value="4" {{ params['report'] == 4 ? 'selected' : ''}} >Ponto</option>
                                    <option value="5" {{ params['report'] == 5 ? 'selected' : ''}} >Atividades Dia</option>
                                </select>
                            </div>
                        </div>
                    </fieldset>
                    <div id="paramsPanel">
                        <fieldset>
                            <legend>Filtros</legend>
                            <div class="col-lg-10 col-lg-offset-1">
                                <div class="row">
                                    <div class="form-group col-lg-6 col-md-6 col-xs-12 col-sm-6">
                                        <label class="control-label">Data inicial</label>
                                        <div class="input-date input-group date" data-date-format="dd/mm/yy" data-date="{{ params['startDate'] == '' ? date('d/m/y') : params['startDate'] }}">
                                            <span class="input-group-btn add-on">
                                                <button class="btn btn-primary">
                                                    <span class="glyphicon glyphicon-calendar icon-calendar"></span>
                                                </button>
                                            </span>
                                            <input type="text" class="form-control" name="startDate" value="{{ params['startDate'] == '' ? date('d/m/y') : params['startDate'] }}"  />
                                        </div>
                                    </div>
                                    <div class=" col-lg-6 col-md-6 col-xs-12 col-sm-6">
                                        <label class="control-label">Data final</label>
                                        <div class="input-date input-group date" data-date-format="dd/mm/yy" data-date="{{ params['endDate'] == '' ? date('d/m/y') : params['endDate'] }}">
                                            <span class="input-group-btn add-on">
                                                <button class="btn btn-primary">
                                                    <span class="glyphicon glyphicon-calendar icon-calendar"></span>
                                                </button>
                                            </span>
                                            <input type="text" class="form-control" name="endDate" value="{{ params['endDate'] == '' ? date('d/m/y') : params['endDate'] }}"  />
                                        </div>
                                    </div>
                                </div>
                                <div class="row" id="user" style="margin: 10px 0px;">
                                    <div class="">
                                        <label>Usuário <span class="text-danger">*</span></label>
                                        <select disabled="disabled" name="user_id" id="user_id" class="form-control"  style="width: 100%">
                                            <option value="">---Selecione---</option>
                                            {% for u in users %}
                                            <option value="{{u.getId()}}" {{params['user'] == u.getId() ? 'selected' : ''}}>{{u.getName()}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row" id="customer" style="margin: 10px 0px;">
                                    <div class="">
                                        <label>Cliente</label>
                                        <select disabled="disabled" name="customer_id" id="customer_id" class="form-control"  style="width: 100%">
                                            <option value="">---Selecione---</option>
                                            {% for c in customers %}
                                            <option value="{{c.getId()}}" {{params['customer'] == c.getId() ? 'selected' : ''}}>{{c.getName()}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row" id="type" style="margin: 10px 0px;">
                                    <div class="">
                                        <label>Tipo de atividade</label>
                                        <select disabled="disabled" name="type_id" id="type_id" class="form-control"  style="width: 100%">
                                            <option value="">---Selecione---</option>
                                            {% for t in types %}
                                            <option value="{{t.getId()}}" {{params['type'] == t.getId() ? 'selected' : ''}}>{{t.getName()}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="" style="margin-top: 20px">
                                        <button class="btn btn-primary pull-right"
                                                type="submit" title="Pesquisar">
                                            <span class="menu-icon glyphicon glyphicon-search"></span>
                                        </button>
                                        <button class="btn btn-primary pull-right"
                                                type="button" title="Limpar" style="margin-right: 10px "
                                                onclick="try {
                                                            clearParams();
                                                        } catch (e) {
                                                        }
                                                        ;
                                                        return false;">
                                            <span class="menu-icon glyphicon glyphicon glyphicon-ban-circle"></span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{{url('js/report/script.js')}}"></script>
<script type="text/javascript" >
                                                    $('#report_selection').change(function() {
                                                        var newval = $('#report_selection').val();
                                                        $('#user_id').attr('disabled', 'disabled');
                                                        $('#user').find('span.text-danger').css('display', 'inline');
                                                        $('#customer_id').attr('disabled', 'disabled');
                                                        $('#type_id').attr('disabled', 'disabled');
                                                        if (newval !== '') {
                                                            if (newval === '1') { // Users
                                                                $('#paramsForm').attr('action', '{{ url("report/user")}}');
                                                            } else if (newval === '2') { // Activity
                                                                $('#paramsForm').attr('action', '{{ url("report/activity")}}');
                                                                $('#customer_id').removeAttr('disabled');
                                                            } else if (newval === '3') { // Activity type
                                                                $('#paramsForm').attr('action', '{{ url("report/type")}}');
                                                                $('#user_id').removeAttr('disabled');
                                                                $('#customer_id').removeAttr('disabled');
                                                                $('#type_id').removeAttr('disabled');
                                                                $('div#user').find('span.text-danger').css('display', 'none');
                                                            } else if (newval === '4') { // Work
                                                                $('#paramsForm').attr('action', '{{ url("report/work")}}');
                                                                $('#user_id').removeAttr('disabled');
                                                            } else if (newval === '5') { // Activity by day
                                                                $('#paramsForm').attr('action', '{{ url("report/work_detail")}}');
                                                                $('#user_id').removeAttr('disabled');
                                                            }
                                                        } else {
                                                                $('#paramsForm').attr('action', '#');
                                                        }
                                                    });
</script>
{% endblock %}