{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('activitytype/index') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">

            <div class="panel panel-default">
                <div class="panel-heading text-right">
                    <h3 class="panel-title">Relatório</h3>
                </div>
                <div class="panel-body">
                    <div class="container col-lg-10 col-lg-offset-1">
                        <form class="form-horizontal" action="#" method="get">
                            <div class="form-group">
                                <label for="report_selection">Selecione o relatório</label>
                                <select name="report_selection" id="report_selection" class="form-control">
                                    <option value="">---Selecione---</option>
                                    <option value="1">Usuários</option>
                                    <option value="2">Atividades</option>
                                </select>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="panel panel-default" id="paramsPanel" style="display: none;">
                <div class="panel-heading text-right">
                    <h3 class="panel-title">Filtros</h3>
                </div>
                <div class="panel-body">
                    <div class="container col-lg-10 col-lg-offset-1">
                        <form action="#" id="paramsForm" method="get" class="form-inline">
                            <div class="form-group">
                                <label class="control-label">Data inicial</label>

                                <div class="input-date input-group date" data-date-format="dd/mm/yy" data-date="{{ date('d/m/y') }}">
                                    <span class="input-group-btn add-on">
                                        <button class="btn btn-default">
                                            <span class="glyphicon glyphicon-calendar icon-calendar"></span>
                                        </button>
                                    </span>
                                    <input type="text" class="form-control" name="startDate" value="{{ date('d/m/y') }}"  >
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Data final</label>
                                <div class="input-date input-group date" data-date-format="dd/mm/yy" data-date="{{ date('d/m/y') }}">
                                    <span class="input-group-btn add-on">
                                        <button class="btn btn-default">
                                            <span class="glyphicon glyphicon-calendar icon-calendar"></span>
                                        </button>
                                    </span>
                                    <input type="text" class="form-control" name="endDate" value="{{ date('d/m/y') }}"  >
                                </div>
                            </div>
                            <div class="text-right" style="margin-top: 10px">
                                <button class="btn btn-default" type="submit"><span class="menu-icon glyphicon glyphicon-search"></span></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#report_selection').change(function() {
        var newval = $('#report_selection').val();
        if (newval === '') {
            $('#paramsPanel').slideUp();
        } else {
            $('#paramsPanel').slideDown();
            if (newval == 1) {
                $('#paramsForm').attr('action', '{{ url("report/user")}}')
            } else if (newval == 2) {
                $('#paramsForm').attr('action', '{{ url("report/activity")}}')
            }
        }
    });
</script>
{% endblock %}