{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('report/index') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <div class="well">
                <fieldset>
                    <legend>Relatórios | Tipos de Atividade</legend>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">Indicadores</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <table class="table table-responsive">
                                        <thead>
                                            <tr>
                                                <th colspan="3">Totalizadores</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Horas disponíveis</td>
                                                <td class="text-right">{{ result.getIndicators().getAvaliableTime()}}</td>
                                            </tr>
                                            <tr>
                                                <td>Horas alocadas</td>
                                                <td class="text-right">{{ result.getIndicators().getAllocatedNormalTime() }}</td>
                                            </tr>
                                            <tr>
                                                <td>Horas restantes</td>
                                                <td class="text-right">{{ result.getIndicators().getRemainingTime() }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-lg-6">
                                    <table class="table table-responsive">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Tipos de Atividade</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for r in result.getTypeIndicators() %}
                                            <tr>
                                                <td>{{r.getActivityType()}}</td>
                                                <td class="text-right">{{r.getAllocatedTime()}}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <table class="table table-responsive">
                                        <thead>
                                            <tr>
                                                <th colspan="4">Total por Colaborador</th>
                                            </tr>
                                            <tr>
                                                <th>Usuário</th>
                                                <th>Disponível</th>
                                                <th>Alocado</th>
                                                <th class="hidden-xs">Restante</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for r in result.getUserIndicators() %}
                                            <tr>
                                                <td>{{ r.getUserName() }}</td>
                                                <td class="text-right">{{ r.getAvaliableTime() }}</td>
                                                <td class="text-right">{{ r.getAllocatedTime() }}</td>
                                                <td class="text-right hidden-xs">{{ r.getRemainingTime() }}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">Detalhado</h3>
                        </div>
                        <div class="panel-body">
                            <table class="table">

                                <thead>
                                    <tr>
                                        <th class="col-lg-3 col-md-3">Data</th>
                                        <th class="col-lg-3 col-md-3">Usuário</th>
                                        <th class="col-lg-5 col-md-5">Tipo</th>
                                        <th class="col-lg-2 col-md-2">Total</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for r in result.getTypesDetails() %}
                                    <tr>
                                        <td>{{ formatDate(r.getDate(), 'day-only') }}</td>
                                        <td>{{ r.getActivityUser() }}</td>
                                        <td>{{ r.getActivityType() }}</td>
                                        <td class="text-right">{{ r.getAllocated() }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</div>
{% endblock %}