{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('report/index') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Inicio</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <table class="table">

                <thead>
                    <tr>
                        <th class="col-lg-3 col-md-3">Data</th>
                        <th class="col-lg-5 col-md-5">Nome</th>
                        <th class="col-lg-2 col-md-2">Alocado</th>
                        <th class="col-lg-2 col-md-2">Total</th>
                    </tr>
                </thead>

                <tbody>
                    {% for r in results %}
                    <tr>
                        <td>{{ formatDate(r.getDate(), 'day-only') }}</td>
                        <td><a href="{{url('usercrud/view/' ~ r.getUserId())}}">{{ r.getUserName() }}</a></td>
                        <td>{{ r.getUserAllocatedHours() }}</td>
                        <td>{{ formatDate(r.getUserTotalHours(),'HM-only') }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}