{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('activities') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                        <a href="{{ url('activities/new') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                        <a href="{{ url('activities/search') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-search"></span>Pesquisar</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <p>{{ _session.getMessage() }}</p>
            <div class="well">
                <fieldset >
                    <legend>Atividades | Dados</legend>
                    <form action="{{ url('activities/save/') }}" method="post" >


                        <input type="hidden" name="id" value="{{instance.getId()}}">
                        <div class="form-group">
                            <label for="name" >Nome</label>
                            <input type="text" class="form-control" name="name" required placeholder="Nome da Atividade" value="{{instance.getName()}}"/>
                        </div>
                        <div class="form-group">
                            <label for="email" >Descrição</label>
                            <textarea class="form-control" name="description" required >{{instance.getDescription()}}</textarea>
                        </div>
                        <div>
                            <div class="form-group">
                                <label for="cpf" >Prioridade</label>
                                <input type="number" max="100" min="0" class="form-control" name="priority" required value="{{instance.getPriority()}}"/>
                            </div>
                            <div class="form-group">
                                <label for="user" >Responsável</label>
                                <select class="form-control" name="user">
                                    <option value="">---Selecione---</option>
                                    {% for t in users %}
                                    <option value="{{t.getId()}}" {{ t.equals(instance.getUser()) ? 'selected':'' }} >{{t.getName()}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="user" >Cliente</label>
                                <select class="form-control" name="customer_id">
                                    <option value="">---Selecione---</option>
                                    {% for c in customers %}
                                    <option value="{{c.getId()}}" {{ c.equals(instance.getCustomer()) ? 'selected':'' }} >{{c.getName()}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            
                            <div class="form-group">
                                <label for="cpf" >Tipo de Atividade</label>
                                <select class="form-control" name="type">
                                    <option value="">---Selecione---</option>
                                    {% for t in types %}
                                    <option value="{{t.getId()}}" {{ t.equals(instance.getActivityType()) ? 'selected':'' }} >{{t.getName()}}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="status" >Status</label>
                                <select class="form-control" name="status" id="status">
                                    <option value="">---Selecione---</option>
                                    <option value="0" {{ 0 == instance.getStatus() ? 'selected':'' }} >Aberto</option>
                                    <option value="1" {{ 1 == instance.getStatus() ? 'selected':'' }} >Finalizado</option>
                                </select>
                            </div>

                            <div class="form-group col-lg-offset-11">
                                <div class="checkbox">
                                    <label>
                                        <input 
                                            type="checkbox"
                                            name="active"
                                            id="active" {{instance.getActive()?'checked="checked"':''}} />Ativo?
                                    </label>
                                </div>
                            </div>
                            {% if (instance.getId() != null) %}
                            {% if count(instance.getInteractions()) > 0 %} 
                            <fieldset>
                                <legend>Ações</legend>
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th class="col-lg-4 col-xs-4">Usuário</th>
                                            <th class="col-lg-2 col-xs-2">Inicio</th>
                                            <th class="col-lg-2 col-xs-4">Fim</th>
                                            <th class="hidden-xs col-lg-2 ">Total</th>
                                            <th class="col-lg-2  col-xs-1"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for a in instance.getInteractions() %}
                                        <tr>
                                            <td>{{a.getUser().getName()}}</td>
                                            <td>{{formatDate(a.getStartDate())}}</td>
                                            {% if a.getEndDate() == null %}
                                            <td>
                                                {% if _session.getUser().getId() === a.getUser().getId() %}
                                                <div class="input-group form-group col-lg-12 col-md-12">
                                                    <input class="input-sm form-control col-lg-2 col-md-2 col-xs-6 action-input-time"  
                                                           type="time" id="ui-time-input-{{ a.getId() }}"  value="{{date('H:i')}}" />
                                                    <span class="input-group-btn " onclick="return finishAction({{ a.getId() }}, $('#ui-time-input-{{ a.getId() }}').val());">
                                                        <button class="btn btn-sm btn-success">
                                                            <span class="glyphicon glyphicon-floppy-disk"></span>
                                                        </button>
                                                    </span>
                                                </div>
                                                {% endif %}
                                            </td>
                                            {% endif %}
                                            {% if a.getEndDate() != null %}
                                            <td>{{formatDate(a.getEndDate())}}</td>
                                            {% endif %}
                                            <td class="hidden-xs">{{a.getAllocatedTime()}}</td>
                                            <td>
                                                {% if _session.getUser().getId() === a.getUser().getId() %}
                                                <a href="{{ url('activities/remove/'~ instance.getId() ~ '/' ~ a.getId()) }}" onclick="return confirm('Deseja realmente remover esta ação?')">
                                                    <span class=" glyphicon glyphicon-ban-circle"></span>
                                                </a>
                                                {% endif %}
                                            </td>

                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </fieldset>
                            {% endif %}
                            <fieldset class="form-inline" 
                                      style="margin-bottom: 15px;
                                      display:{{ instance.isFinished() or not instance.getActive()?'none':'block'}} ;"
                                      id="newActionPanel" >
                                <legend>Incluir Tempo</legend>
                                <div class="form-group col-lg-4 col-md-4">
                                    <label class="control-label">Data</label>
                                    <div class="input-date input-group date" data-date-format="dd/mm/yy" data-date="{{ date('d/m/y') }}">
                                        <span class="input-group-btn add-on">
                                            <button class="btn btn-primary">
                                                <span class="glyphicon glyphicon-calendar icon-calendar"></span>
                                            </button>
                                        </span>
                                        <input type="text" class="form-control" name="action_date" value="{{ date('d/m/y') }}"  />
                                    </div>
                                </div>
                                <div class="form-group  col-lg-4 col-md-4">
                                    <label for="action_time" >
                                        <span>Inicio</span>
                                    </label>
                                    <input type="time" class="form-control" name="action_start_time" id="action_start_time"/>
                                </div>
                                <div class="form-group col-lg-4 col-md-4">
                                    <label for="action_time" >
                                        <span>Fim</span>
                                    </label>
                                    <input type="time" class="form-control" name="action_end_time" id="action_end_time"/>
                                </div>
                            </fieldset>
                            {% endif %}
                            <div class="form-group pull-right" >
                                <a class="btn btn-danger" href="{{url('activities')}}"  >Cancelar<span class="menu-icon glyphicon glyphicon-ban-circle"></span></a>
                                <button type="submit" class="btn btn-success"  >Salvar<span class="menu-icon glyphicon glyphicon-ok"></span></button>
                            </div>
                        </div>
                    </form>

                    <form id="action_submit" action="{{ url('activities/finish/' ~ instance.getId()) }}" method="post">
                        <input type="hidden" name="finish_end_time" id="finish_end_time" value="" />
                        <input type="hidden" name="action_id" id="action_id" value="" />
                    </form>

                </fieldset>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{{url('js/activities/script.js')}}" ></script>
{% endblock %}
