{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('activities') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Inicio</a>
                        <a href="{{ url('activities/new') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                        <a href="{{ url('activities/search') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Pesquisar</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <p>{{ _session.getMessage() }}</ p>
            <form action="{{ url('activities/save/') }}" method="post">
                <input type="hidden" name="id" value="{{instance.getId()}}">
                <div class="form-group">
                    <label for="name" >Nome</label>
                    <input type="text" class="form-control" name="name" required placeholder="Nome da Atividade" value="{{instance.getName()}}"/>
                </div>
                <div class="form-group">
                    <label for="email" >Descrição</label>
                    <textarea class="form-control" name="description" required >{{instance.getDescription()}}</textarea>
                </div>
                <div class="form-group">
                    <label for="cpf" >Prioridade</label>
                    <input type="number" max="100" min="0" class="form-control" name="priority" required value="{{instance.getPriority()}}"/>
                </div>
                <div class="form-group">
                    <label for="cpf" >Tipo de Atividade</label>
                    <select class="form-control" name="type">
                        <option value="">---Selecione---</option>
                        {% for t in types %}
                        <option value="{{t.getId()}}" {{ t.equals(instance.getActivityType()) ? 'selected':'' }} >{{t.getName()}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="user" >Responsável</label>
                    <select class="form-control" name="user">
                        <option value="">---Selecione---</option>
                        {% for t in users %}
                        <option value="{{t.getId()}}" {{ t.equals(instance.getUser()) ? 'selected':'' }} >{{t.getName()}}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="status" >Status</label>
                    <select class="form-control" name="status">
                        <option value="">---Selecione---</option>
                        <option value="0" {{ 0 == instance.getStatus() ? 'selected':'' }} >Aberto</option>
                        <option value="1" {{ 1 == instance.getStatus() ? 'selected':'' }} >Finalizado</option>
                        
                    </select>
                </div>
                
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="active" {{instance.getActive()?'checked="checked"':''}} class="form-control"/>Ativo?
                        </label>
                    </div>
                </div>
                <div class="form-group text-right" >
                    <a class="btn btn-danger" href="{{url('activities')}}"  >Cancelar<span class="menu-icon glyphicon glyphicon-ban-circle"></span></a>
                    <button type="submit" class="btn btn-success"  >Salvar<span class="menu-icon glyphicon glyphicon-ok"></span></button>
                </div>
            </form>
        </div>
    </div> 
</div>
{% endblock %}