{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('usercrud') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                        <a href="{{ url('usercrud/new') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                        <a href="{{ url('usercrud') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-search"></span>Pesquisar</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <p>{{ _session.getMessage() }}</ p>
            <div class="well">
                <fieldset>
                    <legend>Usuários | Pesquisa</legend>
                    <form action="{{url('usercrud/search')}}" method="get" class="form-horizontal">
                        <div class="form-group">
                            <div class="col-lg-11 col-lg-offset-1">
                                <input type="text" class="form-control " name="search" value="<?= $_GET['search']; ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-1 col-md-2 col-xs-12 col-lg-offset-9 col-md-offset-9">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="active" {{active?'checked="checked"':''}} class="form-control"/>Ativos
                                    </label>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-1 col-xs-12 text-right">
                                <button class="btn btn-primary" type="submit"><span class="menu-icon glyphicon glyphicon-search"></span></button>
                            </div>
                        </div>
                    </form>
                </fieldset>

                <fieldset>
                    <legend>Usuários | Resultado</legend>
                    <table class="table table-responsive table-striped table-hover">
                        <thead class="fixedthead" >
                            <tr>
                                <th class="col-xs-2 col-sm-1" >#</th>
                                <th class="col-xs-4 col-sm-3" >Nome</th>
                                <th class="col-xs-6 col-sm-4" >Email</th>
                                <th class="hidden-xs col-sm-4">Último acesso</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for u in results %}
                            <tr>
                                <td><a href="{{ url('usercrud/view/' ~ u.getId()) }}"><span class=" glyphicon glyphicon-edit "></span></a></td>
                                <td>{{ u.getName() }}</td>
                                <td>{{ u.getEmail() }}</td>
                                <td class="hidden-xs ">{{ formatDate(u.getLastAccess())}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {{ pagination }}
                </fieldset>
            </div>
        </div>
    </div>
</div>
    {% endblock %}