{% extends '../template/adm.phtml' %}
{% block content %}
<div class="col-lg-10 col-md-11 col-xs-12 text-center well" style="float: none;margin: auto" >
    {% if count(userResult) > 0 %}
    <p class="has-success text-left">Seu dia:</p>
    <div class="progress" title="{{userResult.getUserAllocatedHours()}} de um total de {{userResult.getUserTotalHours().format('H:i')}} horas disponíveis">
        <div class="progress-bar" role="progressbar" aria-valuenow="{{userResult.getPercentFinished()}}" aria-valuemin="0" aria-valuemax="100" style="width: {{userResult.getPercentFinished()}}%;" >
            <span class="sr-only">{{userResult.getAvaliable()}} de tempo disponivel no seu dia. </span>
        </div>
    </div>
    <div class="text-right">
        <p class="help-block">{{userResult.getUserAllocatedHours()}} de um total de {{userResult.getUserTotalHours().format('H:i')}} horas</p>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-lg-6 ">
            <div class="panel panel-primary">
                <div class="panel-heading">Produtividade do dia</div>
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="col-lg-6 col-xs-6">Quem</th>
                                <th class="col-lg-3 col-xs-3"><span class="hidden-lg hidden-md">Alcd.</span><span class="hidden-xs">Alocado</span></th>
                                <th class="col-lg-3 col-xs-3"><span class="hidden-lg hidden-md">Disp.</span><span class="hidden-xs">Disponível</span></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for t in userResults %}
                            <tr>
                                <td class="text-left"><a href="{{ url('usercrud/view/' ~ t.getUserId()) }}">{{ t.getUserName() }}</a></td>
                                <td>{{ t.getUserAllocatedHours() }}</td>
                                <td>{{t.getAvaliable()}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer text-right">Total {{prodTotal}}</div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel panel-primary">
                <div class="panel-heading">Atividades do dia</div>
                <div class="panel-body">

                    <table class="table">
                        <thead>
                            <tr>
                                <th class="col-lg-10 col-xs-10">Atividade</th>
                                <th class="col-lg-2 col-xs-2"><span class="hidden-lg hidden-md">Alcd.</span><span class="hidden-xs">Alocado</span></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for r in activityResult.getData() %}
                            <tr>
                                <td class="text-left"><a href="{{ url('activities/view/' ~ r.getActivityId() ) }}">{{ r.getActivityName() }}</a></td>
                                <td class="col-lg-4 col-xs-4">{{ r.getAllocated() }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer text-right">{{activityResult.getTotal()}} atividades ({{activityResult.getFinished()}} concluídas)</div>
            </div>
        </div>
    </div>
    <br />
</div>
{% endblock %}