{% extends '../template/adm.phtml' %}
{% block content %}
<div class="col-lg-10" style="float: none;margin: auto">
    <p>{{ _session.getMessage() }}</ p>
</div>
<div class="col-lg-10 col-md-11 col-xs-12 text-center well" style="float: none;margin: auto" >
    {% if count(userResult) > 0 %}
    <p class="has-success text-left">Seu dia:</p>
    <div class="progress" title="{{formatDate(userResult.getUserAllocatedHours(),'HM-only')}} de um total de {{userResult.getUserTotalHours().format('H:i')}} horas disponíveis">
        <div class="progress-bar" role="progressbar" aria-valuenow="{{userResult.getPercentFinished()}}" aria-valuemin="0" aria-valuemax="100" style="width: {{userResult.getPercentFinished()}}%;" >
            <span class="sr-only">{{userResult.getAvaliable()}} de tempo disponivel no seu dia. </span>
        </div>
    </div>
    <div class="text-right">
        <p class="help-block">{{ formatDate(userResult.getUserAllocatedHours(), 'HM-only')}} de um total de {{userResult.getUserTotalHours().format('H:i')}} horas</p>
    </div>
    {% endif %}

    <div class="row">
        <div class="">
            <div class="panel panel-primary">
                <div class="panel-heading">Produtividade do dia ({{formatDate(currentDate,'day-only')}})</div>
                <div class="panel-body" style="position: relative;height: 200px;overflow: auto">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="col-lg-6 col-xs-6">Quem</th>
                                <th class="col-lg-3 col-xs-3 text-center"><span class="hidden-lg hidden-md">Alcd.</span><span class="hidden-xs">Alocado</span></th>
                                <th class="col-lg-3 col-xs-3 text-center"><span class="hidden-lg hidden-md">Disp.</span><span class="hidden-xs">Disponível</span></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for t in userResults %}
                            <tr>
                                <td class="text-left">
                                    <form id="{{ 'formReportUser' ~ t.getUserId() }}" action="{{ url('report/work_detail/') }}">
                                        <a type="submit" href="#" onclick="$('#{{'formReportUser' ~ t.getUserId() }}').submit();">{{ t.getUserName() }}</a>
                                        <input type="hidden" value="{{ formatDate(currentDate,'day-only') }}" name="endDate" id="endDate" />
                                        <input type="hidden" value="{{ formatDate(currentDate,'day-only') }}" name="startDate" name="startDate" />
                                        <input type="hidden" value="{{ t.getUserId() }}" name="user_id" />
                                    </form>
                                </td>
                                <td>{{ formatDate(t.getUserAllocatedHours(), 'HM-only') }}</td>
                                <td>{{ t.getAvaliable() }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div style="position: absolute;bottom: 0px;width: 90%;right: 0px;text-align: right;padding: 15px;">
                        
                        <a href="{{ url('?d='~formatDate(previousDate, 'day-only')) }}"><<</a>
                        {% if nextDate != null %}
                            <a href="{{ url('?d='~formatDate(nextDate, 'day-only')) }}" style="margin-left: 15px; ">>></a>
                        {% endif %}
                    </div>
                </div>
                <div class="panel-footer text-right">Total {{prodTotal}}</div>
            </div>
        </div>
        <div>
            <div class="panel panel-primary">
                <div class="panel-heading">Atividades do dia</div>
                <div class="panel-body" style="height: 400px;overflow: auto">

                    <table class="table">
                        <thead>
                            <tr>
                                <th class="col-lg-7 col-xs-7">Atividade</th>
                                <th class="col-lg-3 col-xs-3 text-center"><span class="hidden-lg hidden-md">Alcd.</span><span class="hidden-xs">Alocado</span></th>
                                <th class="col-lg-2 col-xs-2 text-center">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for r in activityResult.getData() %}
                            <tr>
                                <td class="text-left"><a href="{{ url('activities/view/' ~ r.getActivityId() ) }}">{{ r.getActivityName() }}</a></td>
                                <td class="">{{ r.getAllocated() }}</td>
                                <td class="">{{ r.isFinished() ? 'Finalizado' : 'Aberto' }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer text-right">{{activityResult.getTotal()}} atividades ({{activityResult.getFinished()}} concluídas)</div>
            </div>
        </div>
        <div>
            <div class="panel panel-primary">
                <div class="panel-heading">Atividades abertas</div>
                <div class="panel-body" style="height: 400px;overflow: auto">

                    <table class="table">
                        <thead>
                            <tr>
                                <th class="col-lg-8 col-xs-10">Atividade</th>
                                <th class="col-lg-2 hidden-xs text-center">Prioridade</th>
                                <th class="col-lg-2 col-xs-2  text-center">Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for r in openActivities %}
                            <tr>
                                <td class="text-left"><a href="{{ url('activities/view/' ~ r.getId() ) }}">{{ r.getName() }}</a></td>
                                <td class="hidden-xs">{{ r.getPriority() }}</td>

                                {% if r.canStart(_session.getUser()) %}
                                <td><a href="{{ url('activities/start/' ~ r.getId() )}}" 
                                       class="glyphicon glyphicon-play"></a></td>
                                {% endif %}
                                {% if r.canFinish(_session.getUser()) %}
                                <td><a href="{{ url('activities/finish/' ~ r.getId() ~ '/' ~ r.canFinish(_session.getUser()).getId() ) }}" 
                                       class="glyphicon glyphicon-stop"></a></td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer text-right"><a href="{{ url('activities') }}">&DDotrahd;</a></div>
            </div>
        </div>
    </div>
    <br />
</div>
<script type="text/javascript">
            function loadDate(d){
            return false;
            }
</script>
{% endblock %}