{% extends 'template/open.phtml' %}
{% block content %}
<style type="text/css">

    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin .checkbox {
        font-weight: normal;
    }
    .form-signin .form-control {
        position: relative;
        font-size: 16px;
        height: auto;
        padding: 10px;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="text"] {
        margin-bottom: -1px;
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>
<div class="container">

    <form class="form-signin" action="{{ url('security/login')}}" role="form" method="post">
        <p>{{_session.getMessage()}}</p>
        <input type="hidden" name="targetUrl" value="{{ targetUrl }}"/>
        <input type="hidden" name="{{tokenKey}}" value="{{tokenValue}}" />
        <p >Por favor, efetue o login para continuar</p>
        <input type="email" class="form-control" name="email" placeholder="Email" required autofocus>
        <input type="password" name="password" class="form-control" placeholder="senha" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
    </form>

</div> 

{% endblock %}