{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                    <li><a href="{{ url('holiday') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                        <a href="{{ url('holiday/new') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                        <a href="{{ url('holiday') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-search"></span>Pesquisar</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9 " role="main">
            <p>{{ _session.getMessage() }}</ p>
            <div class="well">
                <fieldset>
                    <legend>Feriados | Dados</legend>
                    <form action="{{ url('holiday/save/') }}" method="post">
                        <input type="hidden" name="id" value="{{instance.getId()}}">
                        <div class="form-group">
                            <label for="name" >Descrição</label>
                            <textarea class="form-control" name="description" >{{instance.getDescription()}}</textarea>
                        </div>
                        <div class="row form-group">
                            <div class="form-group col-lg-3 col-md-4 col-xs-12 col-sm-6">
                                <label for="date" class="control-label">Data</label>
                                <div class="input-date input-group date" data-date-format="dd/mm/yy" data-date="{{ formatDate(instance.getDate(), 'day-only') }}">
                                    <span class="input-group-btn add-on">
                                        <button class="btn btn-primary">
                                            <span class="glyphicon glyphicon-calendar icon-calendar"></span>
                                        </button>
                                    </span>
                                    <input type="text" class="form-control" name="date" value="{{ formatDate(instance.getDate(), 'day-only') }}"  />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="active" {{instance.getActive()?'checked="checked"':''}} />Ativo?
                                </label>
                            </div>
                        </div>
                        <div class="form-group text-right" >
                            <a class="btn btn-danger" href="{{url('holiday')}}"  >Cancelar<span class="menu-icon glyphicon glyphicon-ban-circle"></span></a>
                            <button type="submit" class="btn btn-success"  >Salvar<span class="menu-icon glyphicon glyphicon-ok"></span></button>
                        </div>
                    </form>
                </fieldset>
            </div>
        </div>
    </div> 
</div>
{% endblock %}
