{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-12" role="main">
            <h2>Configurações</h2>
            <hr />
            <form action="{{ url('config') }}" method="post" class="form-horizontal">

                <h3>Dados da empresa</h3>
                <div class="form-group " >
                    <label for="name" class="col-sm-2 control-label">Nome</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="name" required placeholder="Fornalha Vinhedo" value="Fornalha Vinhedo"/>
                    </div>
                </div>

                <div class="form-group " >
                    <label for="name" class="col-sm-2 control-label">Logo</label>
                    <div class="col-sm-10">
                        <input type="file" name="logo" />
                    </div>
                </div>
                <hr />
                <h3>Endereço</h3>
                <div class="form-group">
                    <label for="email" class="col-sm-2 control-label" >Logradouro</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control " name="logradouro" required placeholder="Rua S.t. cruz"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="number" class="col-sm-2 control-label">Número</label>
                    <div class="col-sm-10">
                        <input type="number" min="1" class="form-control  " name="number" required placeholder="1111"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="aux" class="col-sm-2 control-label">Complemento</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control  " name="aux" required placeholder="casa frente"/>
                    </div>
                </div>
                <div class="form-group" >
                    <label for="district" class="col-sm-2 control-label" >Estado</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="district" id="district">
                            {% for st in states %}
                            <option value="{{st.getId()}}">{{st.getName()}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="form-group" >
                    <label for="city" class="col-sm-2 control-label" >Cidade</label>
                    <div class="col-sm-10">
                        <select class="form-control" name="city" id="city" >
                            {% for ct in cities %}
                            <option value="{{ct.getId()}}">{{ct.getName()}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <hr />
                <h3>Contato</h3>

                <div class="form-group">
                    <label for="email" class="col-sm-2  control-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control" name="email" required placeholder="email@exemplo.com.br" />
                    </div>
                </div>

                <div class="form-group">
                    <label for="phones" class="col-sm-2  control-label">Telefones</label>
                    <div class="col-sm-10">
                        <input type="text" data-role="tagsinput" class="form-control" style="width: 100%" name="phones" value="(41) 98459987, (41) 98459987"/>
                        <p class="help-block">Para adicionar novos números, insira o número e tecle enter</p>
                    </div>
                </div>

                <div class="form-group text-right col-lg-12 col-xs-12" >
                    <button type="submit" class="btn btn-danger"  >Cancelar<span class="menu-icon glyphicon glyphicon-ban-circle"></span></button>
                    <button type="submit" class="btn btn-success"  >Salvar<span class="menu-icon glyphicon glyphicon-ok"></span></button>
                </div>
            </form>

        </div>
    </div> 
</div>
<script type="text/javascript">
    $('#district').change(function() {
        $(this).attr('disabled', 'disabled');
        $.ajax(" {{ url('config/loadCities') }}/" + $(this).val(), {
            complete: function(d) {
                $('#city').html(d.responseText);
                console.log(d.responseText);
                $('#district').removeAttr('disabled');
            },
        });
    });
</script>
{% endblock %}