{% extends "template/open.phtml" %}
{% block content %}
<h2>Cardápio > Especiais {{ catId }}</h2>
<hr />
<h3>Sabores:</h3>
<div class="row text-center" >
    <div class="col-lg-4">
        <img width="140" height="140" class="img-circle " src="{{ url('img/layout/Img1.jpg') }}" alt="First slide">
        <h4>Catupiri</h4>
        <p class="lead">Ingredientes:</p>
        <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#precos">Ver preços</a>
    </div>
    <div class="col-lg-4">
        <img width="140" height="140" class="img-circle " src="{{ url('img/layout/Img1.jpg') }}" alt="First slide">
        <h4>Lombinho</h4>
        <p class="lead">Ingredientes:</p>
        <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#precos">Ver preços</a>
    </div>
    <div class="col-lg-4">
        <img width="140" height="140" class="img-circle " src="{{ url('img/layout/Img1.jpg') }}" alt="First slide">
        <h4>Catupiri</h4>
        <p class="lead">Ingredientes:</p>
        <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#precos">Ver preços</a>
    </div>
    <div class="col-lg-4">
        <img width="140" height="140" class="img-circle " src="{{ url('img/layout/Img1.jpg') }}" alt="First slide">
        <h4>Catupiri</h4>
        <p class="lead">Ingredientes:</p>
        <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#precos">Ver preços</a>
    </div>
    <div class="col-lg-4">
        <img width="140" height="140" class="img-circle " src="{{ url('img/layout/Img1.jpg') }}" alt="First slide">
        <h4>Catupiri</h4>
        <p class="lead">Ingredientes:</p>
        <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#precos">Ver preços</a>
    </div>
    <div class="col-lg-4">
        <img width="140" height="140" class="img-circle " src="{{ url('img/layout/Img1.jpg') }}" alt="First slide">
        <h4>Catupiri</h4>
        <p class="lead">Ingredientes:</p>
        <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#precos">Ver preços</a>
    </div>
    <div class="col-lg-4">
        <img width="140" height="140" class="img-circle " src="{{ url('img/layout/Img1.jpg') }}" alt="First slide">
        <h4>Catupiri</h4>
        <p class="lead">Ingredientes:</p>
        <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#precos">Ver preços</a>
    </div>
    <div class="col-lg-4">
        <img width="140" height="140" class="img-circle " src="{{ url('img/layout/Img1.jpg') }}" alt="First slide">
        <h4>Catupiri</h4>
        <p class="lead">Ingredientes:</p>
        <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
        <a href="#precos">Ver preços</a>
    </div>
</div>
<a id="precos">&lrm;</a>
<hr />
<h3>Preços</h3>
<div class="row">
    <div class="col-lg-4">
        <h4>Massa fina pequena</h4>
        <p >R$: 30,00</p>
    </div>
    <div class="col-lg-4">
        <h4>Massa grossa pequena</h4>
        <p >R$: 30,00</p>
        <p >Com borda recheada R$: 32,00</p>
    </div>
    <div class="col-lg-4">
        <h4>Massa grossa pequena</h4>
        <p >R$: 30,00</p>
        <p >Com borda recheada R$: 32,00</p>
    </div>
    <div class="col-lg-4">
        <h4>Massa grossa pequena</h4>
        <p >R$: 30,00</p>
        <p >Com borda recheada R$: 32,00</p>
    </div>
    <div class="col-lg-4">
        <h4>Massa grossa pequena</h4>
        <p >R$: 30,00</p>
        <p >Com borda recheada R$: 32,00</p>
    </div>
</div>

{% endblock %}