{% extends "template/open.phtml" %}
{% block content %}
<h2>Quem somos</h2>
<p class="text-justify" >
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla enim non mi pulvinar, sit amet fringilla magna feugiat. Sed porta consectetur libero in gravida. Morbi lacinia venenatis tincidunt. Duis nisi orci, blandit id dignissim at, lacinia ut quam. Duis ac molestie sem. Nunc sit amet felis lobortis, varius elit nec, facilisis leo. Donec at imperdiet mi, vel vestibulum velit. Nunc sollicitudin, arcu sed placerat dignissim, ante erat sollicitudin felis, eu laoreet orci purus sit amet elit. Fusce in aliquam elit. Nulla laoreet leo quis pulvinar accumsan. Integer id nisl porttitor, consequat augue id, viverra sem. Proin ullamcorper viverra justo, eget venenatis mi ullamcorper eget.

    In sed nunc sit amet libero gravida accumsan. Fusce sagittis venenatis arcu, sed pellentesque metus varius vel. Proin pulvinar, dui et pellentesque luctus, nibh arcu gravida mi, sit amet placerat tellus erat eget sem. Duis eleifend viverra magna non facilisis. Nam sit amet magna non augue feugiat vulputate. Nullam lacus augue, mollis vel tempor in, tempor ac eros. Cras ut suscipit leo. Nam ante purus, vehicula sit amet placerat sed, fringilla aliquet leo. Morbi aliquam elit sit amet urna aliquet, tempus iaculis nisl ornare. In at est eget magna egestas convallis. Mauris semper nec urna lobortis eleifend. Curabitur adipiscing ullamcorper nisl at eleifend. 
</p>
{% endblock %}