{% extends "template/open.phtml" %}
{% block content %}
<h2>Contato</h2>
<p class="text-justify">Para nos contactar você pode utilizar o seguinte formunlário ou, se desejar, utilize o telefone disonível no rodapé da página.</p>
<form role="form" action="{{ url('static/contact') }}" method="post">
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" placeholder="exemplo@email.com">
    </div>
    <div class="form-group">
        <label for="email">Nome</label>
        <input type="text" class="form-control" id="name" placeholder="Meu Nome">
    </div>
    <div class="form-group">
        <label for="mensagem">Mensagem</label>
        <textarea class="form-control" id="mensagem" ></textarea>
    </div>
    <div class="form-group">
        <div class="checkbox">
            <label>
                <input type="checkbox" checked="checked" > Receber atualizações
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-default">Enviar</button>
</form>
{% endblock %}