{% extends '../template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                    <li><a href="{{ url('activitytype') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Inicio</a>
                        <a href="{{ url('activitytype/view') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                        <a href="{{ url('activitytype') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Pesquisar</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <p>{{ _session.getMessage() }}</ p>
            <form action="{{ url('activitytype/save/') }}" method="post">
                <input type="hidden" name="id" value="{{instance.getId()}}">
                <div class="form-group">
                    <label for="name" >Nome</label>
                    <input type="text" class="form-control" name="name" required placeholder="Nome da atividade" value="{{instance.getName()}}"/>
                </div>
                <div class="form-group">
                    <label for="name" >Descrição</label>
                    <textarea class="form-control" name="description" >{{instance.getDescription()}}</textarea>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="active" {{instance.getActive()?'checked="checked"':''}} class="form-control"/>Ativo?
                        </label>
                    </div>
                </div>
                <div class="form-group text-right" >
                    <a class="btn btn-danger" href="{{url('activitytype')}}"  >Cancelar<span class="menu-icon glyphicon glyphicon-ban-circle"></span></a>
                    <button type="submit" class="btn btn-success"  >Salvar<span class="menu-icon glyphicon glyphicon-ok"></span></button>
                </div>
            </form>
        </div>
    </div> 
</div>
{% endblock %}